name: Deploy
on:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.18

      - name: Install node dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
